### ISSUE TITLE
Add pagination or load more for blog posts in - `posts` & `series`

### ISSUE THREAD

**Issue by copypasteov** [AnguHashBlog/angular-primeng#2]
**Additional context**
Right now the existing blog query is retrieving the first 10 blog posts, this is the initial state to get things going.
A pagination needs to be implemented that when the user navigates to the next page a different query is used to retrieve the next 10 posts and the next and so on.

In the query this is done by specifying `after 10`  I believe.

**Comment by czBalazs98** [comment]
I did some research in the HashNode API documentation, in publication querying only the cursor based pagination is possible which is ideal for infinite scrolling. Is it okay for you that we will have load on scroll mechanism for these views? @monacodelisa @cleancodecraft

**Comment by monacodelisa** [comment]
@czBalazs98 I am very pleased to hear that you looked it up :) 
one more thing to do now did you check if it has been implemented in one of the other app versions ad the guide from discussions advises 

![image](https://github.com/AnguHashBlog/angular-primeng/assets/64324417/9d2a0f1f-5c0f-4963-9586-fab64d9372fc)

I believe that the - [angular version](https://github.com/AnguHashBlog/angular) includes an implementation of this feature.

If i remember correctly the implementation is the same as the one you are intending for, if it is what you have in mind and it is already implemented in another app version you are safe to go for it 👍 

of course too if you believe you have any better suggestions feel free to share them too

**Comment by czBalazs98** [comment]
ah yes I see now, didn't have that in mind sorry, I will check it, thank you!

**Comment by monacodelisa** [comment]
@czBalazs98 every fix and feature is temporary - until we find a better one :)
