### ISSUE TITLE
Query and display `co-author` or `co-authors` if any

### ISSUE THREAD

**Issue by monacodelisa** [AnguHashBlog/angular-primeng#25]
**Describe the solution you'd like**
- perform a check to see if the blog is a `team` blog - this check is already done in header 
- if it is a team blog, query and check if there a re any `co-authors` for a blog post
- display and style the image of the `co-author`

**Additional context**
it looks like this in Hashnode 
![image](https://github.com/AnguHashBlog/angular/assets/64324417/d901b62f-4333-4328-8529-439d6f6e1dec)

**Comment by DongreJaipal** [comment]
.take
