### ISSUE TITLE
Add a scroll to top icon / button for longer pages

### ISSUE THREAD

**Issue by samplelittlered** [AnguHashBlog/angular-primeng#28]
**Describe the solution you'd like**
For long blog posts there should be a scroll to pop button / icon that returns the user to the beginning of the page 
- for this app version `primeicons` should be used
- applied in the app.component should be fine

**Comment by monacodelisa** [comment]
@DongreJaipal can you also comment here so I can assign this completed issue to you

**Comment by DongreJaipal** [comment]
.take
