### ISSUE TITLE
Limit the blog post `title` length to 3 rows ~90 characters

### ISSUE THREAD

**Issue by monacodelisa** [AnguHashBlog/angular-primeng#30]
**Describe the solution you'd like**
- for longed blog post titles, limit the displayed title to ~90 characters so it fits in 3 rows 
- adjust in `posts` component and `series` component
- follow the implementation from the `angular` version where it has been applied
- using the `SlicePipe` 

what it look like now:
![image](https://github.com/AnguHashBlog/angular/assets/64324417/49894f27-a488-4682-bca3-dbcd18963a39)

what would be better:
![image](https://github.com/AnguHashBlog/angular/assets/64324417/bfa92c16-f88c-4763-939a-e3e4b02e0237)

**Comment by kapilG0** [comment]
.take
