### ISSUE TITLE
Set the page position for `post-details` to always start at the very top OnInit

### ISSUE THREAD

**Issue by monacodelisa** [AnguHashBlog/angular-primeng#41]
**Describe the solution you'd like**
- angular takes previous page position
- adjust `post-details` so that the content is loading from the very top and you are not lower on the `y-index` of the page
- to be implemented within the `OnInit` lifecycle in the `post-details` component
- using the `ViewportScroller` see implementatinon [here](https://github.com/AnguHashBlog/anguhashblog/blob/main/anguhashblog-app/src/app/app.component.ts)

**Comment by DongreJaipal** [comment]
i can take @monacodelisa
