### ISSUE TITLE
Feature: author and co-authors to be clickable links leading to the author's page on Hashnode

### ISSUE THREAD

**Issue by monacodelisa** [AnguHashBlog/angular-primeng#61]
### Type of feature

✨ Feature

### Current behavior

The Author's & co-Authors image is not clickable

### Suggested solution

Author and co-authors images should be wrapped in an anchor tag (link element) and should lead to the authors profile page on Hashnode which has this format:
```
https://hashnode.com/@cleancodecraft
```
So the author's name needs to be mapped with a variable to the matching author or co-author

### I would be willing to submit a PR to fix this issue

- [X] Yes and I have read the [Contribution Guide](https://anguhashblog.com/contributing) and I agree to follow this project's [Code of Conduct](https://anguhashblog.com/code-of-conduct)
- [ ] No

**Comment by DongreJaipal** [comment]
.take
