### ISSUE TITLE
Bug: Inconsistency in GraphQL Query for Author Data

### ISSUE THREAD

**Issue by monacodelisa** [AnguHashBlog/angular-primeng#74]
### Describe the bug

We need to address an inconsistency in our GraphQL query that retrieves author data from Hashnode's API. 

- In the file `graphql.operations.ts` on lines 139 and 175, the query should be changed, we need to get:
- `id`
- `name`
- and `username` should be added too
- verify that cases are for the `author`.

![image](https://github.com/AnguHashBlog/angular-primeng/assets/64324417/89022808-c0fa-46d2-b40a-92b3abc8674c)

- in the `post.ts` file, the author interface should be adjusted, the `usarname` property needs to be added 

![image](https://github.com/AnguHashBlog/angular-primeng/assets/64324417/6ac85b74-8345-44a6-84d7-7e8c820f89ec)

### To see the changes 

- in the `post-details` component we need to change `post.author.name` to `post.author.username`

![image](https://github.com/AnguHashBlog/angular-primeng/assets/64324417/52b7c9c6-adbb-4cf6-a2b9-16a391d3db6a)

### Browsers

Chrome

### I would be willing to submit a PR to fix this issue

- [X] Yes and I have read the [Contribution Guide](https://anguhashblog.com/contributing) and I agree to follow this project's [Code of Conduct](https://anguhashblog.com/code-of-conduct)
- [ ] No

**Comment by MestiriBaha** [comment]
@monacodelisa  I would love to work on this issue !

**Comment by monacodelisa** [comment]
@MestiriBaha you are now assigned :) if you have any questions - ask here or in the [angular-primeng discord channel](https://discord.gg/YyV2z8Y6)
